# Generated by Django 4.0.5 on 2022-06-19 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTable',
            fields=[
                ('booking_date', models.DateField(primary_key=True, serialize=False)),
                ('time_slot_12', models.PositiveSmallIntegerField(default=10)),
                ('time_slot_14', models.PositiveSmallIntegerField(default=10)),
                ('time_slot_16', models.PositiveSmallIntegerField(default=10)),
                ('time_slot_18', models.PositiveSmallIntegerField(default=10)),
                ('time_slot_20', models.PositiveSmallIntegerField(default=10)),
                ('time_slot_22', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'ordering': ['booking_date'],
            },
        ),
        migrations.CreateModel(
            name='User_Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateField()),
                ('booked_time', models.CharField(max_length=6)),
                ('booked_tables', models.PositiveSmallIntegerField()),
                ('booked_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
