# Generated by Django 4.0.5 on 2022-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcomments', '0004_alter_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
