# Generated by Django 4.0.5 on 2022-06-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('allergies', models.TextField()),
                ('image', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MenuMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('allergies', models.TextField()),
                ('image', models.URLField(max_length=250)),
            ],
        ),
    ]
